### ISSUE TITLE
Question concerning angular meteor.

### ISSUE THREAD

**Issue by vacarsu** [NickTomlin/braintree-meteor-example#3]
Will the braintree client work in angular-meteor?

**Comment by NickTomlin** [comment]
I haven't tried it personally, but I don't see any reason it should not work. There are some additional considerations when working with SPAs and drop-in. I'd suggest taking a look at [braintree-angular](https://www.npmjs.com/package/braintree-angular) as well.

**Comment by vacarsu** [comment]
That looks good thanks.

**Comment by vacarsu** [comment]
How do I include an npm module within an angular module?

Normally it's done like

```
SetModule('vdexter', [
  'angular-meteor',
  'braintree-angular'
])
```

Now obviously that's not going to work in meteor, so I tried this

```
SetModule('vdexter', [
  'angular-meteor',
  Meteor.npmRequire('braintree-angular').name
])
```

But I don't think Meteor.npmRequire is available on the client. If you're wondering what the SetModule is all about, it's exactly the same as angular.module. I'm using angular2-now.

**Comment by NickTomlin** [comment]
In this project, i've done this by [adding the files to the client within a custom package](https://github.com/NickTomlin/braintree-meteor-example/blob/master/packages/nicktomlin:braintree-example/package.js#L10) but there is probably a better way. Those would be exposed on the window and available within your angular code without needing to inject them. 

Angular2 is a whole different ball game, since it's still in alpha and I can't give you specific advice there.

Unfortunately I won't be able to provide more support than the little advice that I have. I'd recommend reaching out to folks focused on Meteor development.

**Comment by vacarsu** [comment]
To be precise it's angular 1.4, angular2-now is a library which allows you to use alot of angular 2's syntax in angular 1.x. I am currently trying to use browserify to import the braintree-angular package, but I get an error navigator is undefined.

**Comment by vacarsu** [comment]
Okay I got it working on the server side, however when I try to create a customer I get the following error:

```
Exception while invoking method 'createBusinessCustomer' TypeError: Cannot read property 'http' of undefined
I20150708-17:02:55.252(-7)?     at CustomerGateway.create (/Users/alex/Desktop/vdexter/vdexter/.meteor/local/isopacks/npm-container/npm/node_modules/braintree/lib/braintree/customer_gateway.js:26:24)
I20150708-17:02:55.252(-7)?     at packages/meteor/helpers.js:118:1
I20150708-17:02:55.252(-7)?     at [object Object].Meteor.methods.createBusinessCustomer (app/server/startup/braintree.js:16:15)
I20150708-17:02:55.253(-7)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150708-17:02:55.253(-7)?     at packages/ddp/livedata_server.js:648:1
I20150708-17:02:55.253(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150708-17:02:55.253(-7)?     at packages/ddp/livedata_server.js:647:1
I20150708-17:02:55.254(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150708-17:02:55.254(-7)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150708-17:02:55.254(-7)?     at packages/ddp/livedata_server.js:546:1
```

The method I am using:

``` javascript
var createCustomer = Meteor.wrapAsync(gateway.customer.create);
    var response = createCustomer({
      firstName: user.firstName,
      lastName: user.lastName,
      company: user.organizationName,
      email: user.email,
      phone: user.organizationNumber,
      website: user.organizationWebsite
    }, function (err, result) {
      if (err)
        return console.log(err);

      console.log(result.customer.id)
      return result.customer.id;
    })

    return response;
```
